version: 2

exit_zero: false
verbose: false
instance: https://dashboard.gitguardian.com

secret:
  ignored_matches:
    - match: "*EXAMPLE_*"
      name: demo credentials for testing purposes
  ignored_paths:
    - '**/README.md'
    - docs/*
    - LICENSE
